apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minikube-ingress
  annotations:
spec:
  rules:
  - host: hello.world
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: clientlayer
            port:
              number: 8501
      - path: /applicationlayer(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: applicationlayer
            port:
              number: 8000
      - path: /datalayer(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: datalayer
            port:
              number: 8001
      - path: /mllayer(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: mllayer
            port:
              number: 8002
      - path: /optimizationlayer(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: optimizationlayer
            port:
              number: 8003
      - path: /utilitylayer(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: utilitylayer
            port:
              number: 8004