---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicationlayer-deployment
  labels:
    name: applicationlayer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applicationlayer
  template:
    metadata:
      labels:
        app: applicationlayer
    spec:
      containers:
      - name: applicationlayer
        image: applicationlayer
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: applicationlayer-service
  labels:
    service: applicationlayer
spec:
  selector:
    app: applicationlayer
  ports:
  - port: 8000
    targetPort: 8000