---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientlayer-deployment
  labels:
    name: clientlayer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientlayer
  template:
    metadata:
      labels:
        app: clientlayer
    spec:
      containers:
      - name: clientlayer
        image: clientlayer
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: clientlayer-service
  labels:
    service: clientlayer
spec:
  selector:
    app: clientlayer
  ports:
  - port: 80
    targetPort: 80