version: '3.8'

services:
  web:
    build: ./login
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./login:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://pguser:pgpassword@db:5432/foo
    depends_on:
      - db
  db:
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=foo